# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code_snippets_2021_05_29/user_2_optional.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='code_snippets_2021_05_29/user_2_optional.proto',
  package='user_2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.code_snippets_2021_05_29/user_2_optional.proto\x12\x06user_2\".\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x03\x61ge\x18\x02 \x01(\rH\x00\x88\x01\x01\x42\x06\n\x04_ageb\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='user_2.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='user_2.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='user_2.User.age', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_age', full_name='user_2.User._age',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=58,
  serialized_end=104,
)

_USER.oneofs_by_name['_age'].fields.append(
  _USER.fields_by_name['age'])
_USER.fields_by_name['age'].containing_oneof = _USER.oneofs_by_name['_age']
DESCRIPTOR.message_types_by_name['User'] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'code_snippets_2021_05_29.user_2_optional_pb2'
  # @@protoc_insertion_point(class_scope:user_2.User)
  })
_sym_db.RegisterMessage(User)


# @@protoc_insertion_point(module_scope)
